name: AnalyticSubgraph

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths: [
      'src/airas/analysis/analytic_subgraph/**',
      'tests/integration/test_analytic_subgraph.py',
      'tests/unit/analysis/analytic_subgraph/**',
      '.github/workflows/pytest_analytic_subgraph.yml'
    ]

defaults:
  run:
    shell: bash

jobs:
  test-analytic-subgraph:
    name: AnalyticSubgraph Components
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - test_name: analytic_node
            test_file: tests/unit/analysis/analytic_subgraph/test_analytic_node.py
          - test_name: integration_test_for_analytic_subgraph
            test_file: tests/integration/test_analytic_subgraph.py
    env:
      GITHUB_WORKSPACE: ${{ github.workspace }}
      SAVE_DIR: ${{ github.workspace }}/save_dir

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/0.5.5/install.sh | bash || exit 1
          uv --version

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/src" >> $GITHUB_ENV
      
      - name: Create Directory
        run: mkdir -p $SAVE_DIR
      
      - name: Run pytest with coverage
        run: uv run pytest --cov=airas.analytic_subgraph --cov-branch --cov-report=term-missing -v ${{ matrix.test_file }}

      - name: Ensure pip cache folder exists
        run: mkdir -p /home/runner/.cache/pip

