name: ExperimentalPlanSubgraph

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths: [
      'src/airas/create/create_experimental_design_subgraph/**',
      'tests/integration/create_experimental_design_subgraph.py',
      'tests/unit/create/create_experimental_design_subgraph/**',
      '.github/workflows/pytest_create_experimental_design_subgraph.yml'
    ]

defaults:
  run:
    shell: bash

jobs:
  test-experimental-plan-subgraph:
    name: ExperimentalPlanSubgraph Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - test_name: generate_advantage_criteria
            test_file: tests/unit/create/create_experimental_design_subgraph/test_generate_advantage_criteria.py
          - test_name: generate_experiment_details
            test_file: tests/unit/create/create_experimental_design_subgraph/test_generate_experiment_details.py
          - test_name: generate_experiment_code
            test_file: tests/unit/create/create_experimental_design_subgraph/test_generate_experiment_code.py
    env:
      GITHUB_WORKSPACE: ${{ github.workspace }}
      SAVE_DIR: ${{ github.workspace }}/save_dir
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/0.5.5/install.sh | bash || exit 1
          uv --version
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/src" >> $GITHUB_ENV
      - name: Create Directory
        run: mkdir -p $SAVE_DIR
      - name: Run pytest with coverage
        run: uv run pytest --cov=airas.experimental_plan_subgraph --cov-branch --cov-report=term-missing -v ${{ matrix.test_file }}
      - name: Ensure pip cache folder exists
        run: mkdir -p /home/runner/.cache/pip
